---

ansible_ssh_host: "{{ __network.nas.production.baseAddr | ansible.utils.ipaddr('address') }}"
ansible_ssh_user: "{{ __login_nas_ssh_user }}"
ansible_ssh_pass: "{{ __login_nas_ssh_passwd }}"
ansible_sudo_pass: "{{ __login_nas_ssh_passwd }}"

