---

web:
  hosts:
    vps.A:
      __extra_domains:
        - "*.{{ __frp.vps.A.prefix }}.frp.{{ __domain_basename }}"
    vps.B:
      __extra_domains:
        - "*.{{ __frp.vps.B.prefix }}.frp.{{ __domain_basename }}"
  vars:
    __certbot_domains:
      - "{{ __domain_basename }}"         # basic domain
      - "*.{{ __domain_basename }}"       # basic sub-domain
      # port sub-domain
      - "*.port.{{ __domain_basename }}"
      - "*.frp.{{ __domain_basename }}"
      # docker sub-domain
      - "*.docker.{{ __domain_basename }}"
    certbot__domains:
      - name: "{{ __domain_basename }}"
        domains: "{{ __certbot_domains + __extra_domains | default([]) }}"
    certbot__dns_plugin: "{{ __certbot__dns_plugin }}"
    certbot__dns_api_token: "{{ __certbot__dns_api_token }}"

    docker_compose_app__dir_base: /app
    registry__domain:
      base: "docker.{{ __domain_basename }}"
      ports:
        ghcr.io:
          subdomain: ghcr
          remoteurl: https://ghcr.io
    registry__secret:
      ui_keybase: "{{ __web__docker_registry_secret }}"
    registry__port: 127.0.0.1:5000

