---

- name: Test nginx
  ansible.builtin.command: nginx -t

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: "nginx"
    state: reloaded

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: "nginx"
    state: restarted

