---

- import_tasks: install.yml

- name: Set Certbot script variable.
  ansible.builtin.set_fact:
    certbot__script: "certbot"

- import_tasks: set_vars.yml

- import_tasks: prepare.yml

- include_tasks: create_cert.yml
  with_items: "{{ _certbot__domains }}"
  loop_control:
    loop_var: cert_item

