---

- name: import Oefenweb.ansible-dnsmasq role to setup dns since OS != "OpenWrt"
  include_role:
    name: Oefenweb.ansible-dnsmasq
  when: ansible_facts["os_family"] != "OpenWrt"

- name: include the dns setup for OpenWrt devices
  include_tasks: openwrt.yml
  when: ansible_facts["os_family"] == "OpenWrt"
